### ISSUE TITLE
Drug Dictionary is returning 404 error page on appending /expand to the url

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/drug-dictionary-app#100]
### Issue description

Currently, Drug Dictionary is returning 404 error page (Page Not Found) on appending /expand to the landing page url . When user appends "/expand" to the URL and tries to go to this URL, the system should return the "No Matches Found" page. (https://github.com/NCIOCPL/drug-dictionary-app/issues/4)

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://www.cancer.gov/publications/dictionaries/cancer-drug/expand
2. 404 error page is returned

### What's the expected result?
- When user appends "/expand" to the URL and tries to go to this URL, the system should return the "No Matches Found" page. (https://github.com/NCIOCPL/drug-dictionary-app/issues/4)

### What's the actual result?
-  404 error page (Page Not Found) is returned 

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/103571357-bb577a80-4e98-11eb-88bd-ecfbd70cdf09.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
Closing this issue because it should show a PNF. This is not a valid path for our app - if you're using /expand, it needs to have a letter associated.
