### ISSUE TITLE
Update npm security vulnerabilities

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/drug-dictionary-app#117]
There are a number of security vulnerabilities that should be fixed via `npm audit fix`.

**> **ESTIMATE** 2**

### Notes
- This has the potential to break things as dependencies are updated to newer versions. Application functionality must be tested thoroughly.

**Comment by seyilonge-nci** [comment]
- An `npm audit` report generated the file attached below
[dd-app-npm-audit-report-before.txt](https://github.com/NCIOCPL/drug-dictionary-app/files/9577206/dd-app-npm-audit-report-before.txt)

- Ran `npm audit fix` successfully

- `npm run test` ran successfully with no errors

- Running `npm audit` generated file attached below
[dd-app-npm-audit-report-after.txt](https://github.com/NCIOCPL/drug-dictionary-app/files/9577208/dd-app-npm-audit-report-after.txt)
