### ISSUE TITLE
Story: Redirect to Pretty URL

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/drug-dictionary-app#13]
## As the website, I should redirect CDR IDs in URLs to its counterpart pretty URL for better findability.

> **ESTIMATE** XXX

### Acceptance Criteria

```gherkin
Scenario: Redirect from CDR ID
  Given user enters /def/42265 as the URL
  Then the system redirects user to /def/trastuzumab
  And the system appends ?redirect=true to the URL
Examples:
| CDR ID | URL Redirect|
| 43234 | bevacizumab |
| 484642 | jin-fu-kang |
| 269682 | juvin |
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by arcepaul** [comment]
closed by PR #30
