### ISSUE TITLE
Adding "Rx Patient Information" Button on Search Result Page (ON HOLD; NOT PART OF MIGRATION)

### ISSUE THREAD

**Issue by venglisch** [NCIOCPL/drug-dictionary-app#18]
When a drug term is listed for which a Drug Information Summary document exists a link/button with the label "Rx Patient Information" is displayed after the term name. For instance, see bevacizumab:
https://www.cancer.gov/publications/dictionaries/cancer-drug?CdrID=43234

This label is only displayed on the page for the drug term. The users would like this link to be included on a search result page as well:
https://www.cancer.gov/publications/dictionaries/cancer-drug?search=beva

**Comment by lburack** [comment]
Please note, this ticket is not part of current/upcoming sprints for the migration. A better understanding of user intent for the search results page is needed before we implement this change.

**Comment by amydugan** [comment]
Closing - will implement in https://github.com/NCIOCPL/drug-dictionary-app/issues/27
