### ISSUE TITLE
Story: Clinical Trials/NCI Thesaurus Links on Term Page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/drug-dictionary-app#28]
## As a user, I would like to find active clinical trials and learn more about a drug from the NCI Thesaurus so that I may be more informed about the cancer drug and my trial options.

> **ESTIMATE** 

### Acceptance Criteria

```gherkin
Scenario: As a user, I would like to see a link to active clinical trials when I am viewing a term page
  Given "dynamicListingPageBase" is set to "https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention"
     And "nciThesaurusConceptLinkPattern" is set to "https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=${CCODE}"
  When the user is viewing the definition with the url /def/bevacizumab
  Then an active clinical trials link to "https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/C2039" appears after the definition text
    And an NCI Thesaurus link to "https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039" EVS appears after the clinical trials link  
```

```gherkin
Scenario: As a user, I would like to see a link to the NCI Thesaurus entry for that drug when I am viewing a term page
  Given "dynamicListingPageBase" is set to "https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention"
     And "nciThesaurusConceptLinkPattern" is set to "https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=${CCODE}"
  When the user is viewing the definition with the url /def/bevacizumab
  Then an NCI Thesaurus link to "https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039" EVS appears after the clinical trials link  
```

```gherkin
Scenario: negative: As a user, I do not see see a clinical trials or NCI Thesaurus link when it is not provided
  Given the user is viewing the definition with the url /def/801361
    And the page title is "A2A receptor antagonist EOS100850"
  Then the "Check for active clinical trials using this agent" link does not appear on the page
    And the "View this agent in the NCI Thesaurus" link does not appear on the page
```

### Resources:
* Mockups: https://publicis.invisionapp.com/share/QDYHYSLCBZY#/screens/429245338

### Notes
* See mockup for changes to the link text and display.
* The "active clinical trials link" refers to the text, `Check for active clinical trials using this agent` and the URL points to the "Intervention Dynamic Listing Page" and has the format of https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/[C-Code or Pretty Url] where C-Code is the NCIConceptId element from the API and Pretty Url is the PrettyUrlName parameter.
  * NOTE: The pretty urls will be out of sync with the dynamic listing pages until the dynamic listing pages are moved to react. So use the C-Code for now.
* "an NCI Thesaurus link" refers to the text `View this agent on the NCI Thesaurus` which links to the corresponding NCI Thesaurus entry (URL: https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=[C Code] where C-Code is the NCIConceptId from the API)

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by amydugan** [comment]
Closed by PR https://github.com/NCIOCPL/drug-dictionary-app/pull/35
