### ISSUE TITLE
Add Analytics Tagging to Patient Button on Drug Summary items

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/drug-dictionary-app#37]
### Issue description
This ticket is to add analytics tagging to the Patient Information button found on the drug dictionary term pages for drug terms that have that button appear at the top of them.

> **ESTIMATE** 20

### What's the expected change?
Currently, there is no analytics event associated with clicks on that button, so this ticket will be to add that tagging as a click event when a user clicks on the button and to pass the needed information through to Adobe Analytics via Launch.

On click of the button an analytics click event should be fired and the following values should be sent off to Adobe Analytics:
* prop66 - this variable will pass an value to help identify the type of click. This value should be [analytics dictionary name]_patientinfo_button. The [analytics dictionary name] I believe is a value that exists already for each dictionary, we should use the drug dictionary value for this piece of the value.
* prop67 - this variable will pass the pagename value. I think it is already configured to fire on all click events.
* Event82 - this variable will be fired each time the button is clicked.

These specific analytics values will need to be configured in Adobe Launch, but will utilize the information referenced in the acceptance criteria.

### What's the current functionality?
A user clicks on the patient information button on the dictionary term page and is taken to the associated drug summary with no analytics event fired on click of the button.

### What's the updated acceptance criteria?
```gherkin
Scenario: Analytics fires when a user clicks on a BestBet title link with one best bet
        Given "dictionaryTitle" is set to "NCI Drug Dictionary"
         And "siteName" is set to "National Cancer Institute"
        And "channel" is set to "Publications"        
        And "analyticsPublishedDate" is set to "02/02/2011"
            When the user navigates to bevacizumab definition page
           When user clicks on the "Patient Information" button
            Then there should be an analytics event with the following details
			| key                  | value                           |
			| type                 | Other                           |
			| event                | DrugDictionaryApp:Other:PatientInfoClick |
			| linkName             | PatientInfo_Button |
			| data.dictionaryTitle   | NCI Drug Dictionary |
                        | data.analyticsName   | Drug |
                        | data.term   | bevacizumab |
                        | data.id   | (int) 415570 |

```

```gherkin


### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by kate-mashkina** [comment]
tagging @bryanpizzillo to review and add AC as needed

**Comment by kate-mashkina** [comment]
PR is merged
