### ISSUE TITLE
Synonym names out of order for multiple terms

### ISSUE THREAD

**Issue by karlikpj** [NCIOCPL/drug-dictionary-app#42]
### Issue description
*Description of the issue*

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  go to https://react-app-dev.cancer.gov/drug-dictionary-app/develop/def/crizotinib
2. view Synonym table
3. Note the order (Code Name is before US Brand Name)

### What's the expected result?
- Order should be US Brand Name - then Code Name

### What's the actual result?
- Code Name is before US Brand Name

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

This should be the correct order however for that one term(*that we know of) this order gets out of wack.
https://react-app-dev.cancer.gov/drug-dictionary-app/develop/def/bevacizumab

**Comment by kate-mashkina** [comment]
another example:
prod: https://www.cancer.gov/publications/dictionaries/cancer-drug/def/bicalutamide
react:https://react-app-dev.cancer.gov/drug-dictionary-app/develop/def/bicalutamide

**Comment by kate-mashkina** [comment]
PR is merged
