### ISSUE TITLE
IE issues for Drug dictionary

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/drug-dictionary-app#44]
### Issue description
IE issues:

1. Fonts are different 
2. The text in the View Patient Information Button is more aligned to the top
3. The indentation in the table is not correct
4. The Search button is not aligned with the Search input box

> **ESTIMATE** 20

### Steps to reproduce the issue

1. Go to https://react-app-dev.cancer.gov/drug-dictionary-app/develop/def/sacituzumab-govitecan
2. Note that the fonts are different from Chrome and other browsers
3. Note that the text in the View Patient Information Button is more aligned to the top. (Screen-shot is attached)
4. Note that the indentation in the table is not correct. (Screen-shot is attached)
5. Note that the Search button is not aligned with the Search input box. (Screen-shot is attached)

### What's the expected result?

- The fonts should look same as Chrome and other browsers
- The text in the View Patient Information Button should be center aligned
- All items in the table should be left aligned
- The Search button should be aligned with the Search input box

### What's the actual result?

- The fonts are different from Chrome and other browsers
- The text in the View Patient Information Button is more aligned to the top. 
- The indentation in the table is not correct
- The Search button is not aligned with the Search input box

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/95239400-e8808800-07d8-11eb-9e8f-25910dd18d1b.png)

![image](https://user-images.githubusercontent.com/28455973/95239539-1796f980-07d9-11eb-937e-ae154e5dfaf8.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by kate-mashkina** [comment]
PR is merged
