### ISSUE TITLE
Error page is displaying for Drug dictionary on Edge.

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/drug-dictionary-app#56]
### Issue description
http://ncigovcdode393.prod.acquia-sites.com/publications/dictionaries/cancer-drug/
is throwing error on Edge.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Open new Edge browser 
2. Go to url: http://ncigovcdode393.prod.acquia-sites.com/publications/dictionaries/cancer-drug/

### What's the expected result?
- Drug Dictionary landing page should be displayed.

### What's the actual result?
-'An error occurred. Please try again later.' is displayed.

### Additional details / screenshot
- 
![image](https://user-images.githubusercontent.com/31008800/95912273-9dceb500-0d70-11eb-8be4-455aa98a4d09.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by kate-mashkina** [comment]
This issue was found on ODE - react-app-dev is loading fine for Nadia. This issue needs to be verified once code is deployed to an ODE

**Comment by SupriyaSaxena0605** [comment]
this is working fine for me on Edge. Will verify again once the code is on ODE.

**Comment by VictoriaSunNIH** [comment]
Verified this as working in Edge (URL: https://www-dev-ac.cancer.gov/publications/dictionaries/cancer-drug). Closing this one
