### ISSUE TITLE
The Search input box and Button should appear the same way and should have the same size as other Dictionaries on the site at same breakpoint

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/drug-dictionary-app#57]
### Issue description
The Search input box and Button should appear the same way and should have the same size as other Dictionaries on the site at same breakpoint. For example, at 640px, the button wraps to the next line on the term definition page on Drug Dictionary but on the term definition page of Dictionary of Cancer Terms and Genetics Terms, at 640px, the Search input box and the button appears side by side.
Also, on Drug Dictionary, the Search input box and button is appearing bigger vs, other Dictionaries  at the same tablet and mobile breakpoints.

> **ESTIMATE** 1

### What's the expected change?
- The Search input box and Button should look same and should have same size as other Dictionaries on the site at the same breakpoint (for example at 640px, they should appear the way the Search Input box and button appears in other Dictionaries). 

### What's the current functionality?
- On Drug Dictionary, the Search input box and button is appearing bigger in Drug Dictionary vs, other Dictionaries  at tablet and mobile breakpoints and the button wraps to the next line on the term definition page at the tablet and mobile breakpoint.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- 
![image](https://user-images.githubusercontent.com/28455973/95920110-ceb4e700-0d7c-11eb-8a07-4a38aa10f761.png)

![image](https://user-images.githubusercontent.com/28455973/97599577-86cdcb00-19de-11eb-8dd6-2fa53269aa63.png)

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by mworrest** [comment]
View patient info button needs to be full width at 640 and smaller. I'll open a CR ticket.

**Comment by kate-mashkina** [comment]
According to @mworrest this is an expected behavior, which actually exposed a bug in Glossary

**Comment by kate-mashkina** [comment]
It was decided to have a search button remain on a side due to it being overlapped by autosuggest dropdown

**Comment by mworrest** [comment]
Kate fixed the autosuggest so that a partial search can be done and no items from the dropdown are highlighted by default, Therefore, we can have the search button underneath the search box on mobile because users can hit return on the keyboard.

**Comment by blilianyu** [comment]
This looks good to us! @mworrest @VictoriaSunNIH @lburack
