### ISSUE TITLE
Long term names should be wrapped onto a next line without so much space in the first line

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/drug-dictionary-app#63]
### Issue description
*Description of the issue*
Example url: http://ncigovcdode393.prod.acquia-sites.com/publications/dictionaries/cancer-drug/def/aspirin-simvastatin-atenolol-ramipril-thiazide-capsule

> **ESTIMATE** TBD

### What's the expected change?
The term name should be fit to the max length of the first line before being wrapped onto the next one -  perhaps the delimiter should be the special character connecting two word parts together ( there is no real example in glossary of such a long term, but with resizing the window down a desired wrapping happens here : https://www.cancer.gov/publications/dictionaries/cancer-terms/def/17-n-allylamino-17-demethoxygeldanamycin)
Note: Michelle suggested  to add spaces between the slashes

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/96039370-89ed8680-0e36-11eb-987e-261b1663daed.png)

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by karlikpj** [comment]
The data base name comes out with no spaces in the aliases which doesn't allow us to easily create nice break points. 

<img width="732" alt="screen_shot_2020-10-26_at_10 20 16_am" src="https://user-images.githubusercontent.com/66697447/97615893-3fe9d080-19f2-11eb-8db6-07c0f1c79e1d.png">

We can break via CSS but then we have no control where it breaks and could cause half words/names which make it unreadable. 

<img width="681" alt="screen_shot_2020-10-26_at_10 40 19_am" src="https://user-images.githubusercontent.com/66697447/97615994-5abc4500-19f2-11eb-9fbd-484ee3928c48.png">

**Comment by mworrest** [comment]
Not going to change this. This is how it works on prod currently.

**Comment by amydugan** [comment]
You had me at this is how it works on prod currently. Closing this issue as won't fix.
