### ISSUE TITLE
Autosuggest terms getting hidden by the Mega Menu

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/drug-dictionary-app#98]
### Issue description

When there is not enough space for the autosuggest window to display the drop-down window and they appear as a drop-up window some of the autosuggest terms gets hidden by the megamenu. This happens mostly in Search Results page as there is no intro text on top of the Search bar.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/publications/dictionaries/cancer-drug/search/bevacizumab/?searchMode=Begins 
2. Making sure that you are viewing the top of the page, type "den" in the Search input box.
3. A drop-up window appears and 8 autosuggest terms are visible in the drop-up window and the 2 autosuggest terms gets hidden by the mega menu.
4. Then go to the term definition page  https://www.cancer.gov/publications/dictionaries/cancer-drug/def/bevacizumab 
5. Type "den" in the Search input box  in the term definition page
6. All 10 autosuggest terms are displayed in the drop-down.

### What's the expected result?
- All autosuggest terms should be displayed in the drop-up/drop-down 
- No autosuggest term should get hidden by mega menu.

### What's the actual result?
- Autosuggest terms are getting hidden by mega menu when drop-up menu appears on typing autosuggest term in the Search box.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/100967745-ffeca080-34fd-11eb-9679-67ef374ed9d9.png)

![image](https://user-images.githubusercontent.com/28455973/100967918-5a85fc80-34fe-11eb-965a-55002ebe5655.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
With the release of our redesigned megamenu, this is no longer an issue.
